### ISSUE TITLE
What are the specific technologies that we need to demonstrate experience in?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#100]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

{please be specific about the section of the RFP documents you have a question or comment about, if applicable}
 
## Question/Comment

The RFP states one of the minimum qualifications as – “Demonstrated experience with similar technologies at an enterprise scale”

What are the specific technologies that we need to demonstrate experience in?

**Comment by kelliejulian** [comment]
The technology is described in section 2.01 and 3.01
