### ISSUE TITLE
Can the state provide the current technology stack?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#101]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 1.04 – Minimum Qualifications, page 6 of 40
 
## Question/Comment

The RFP states one of the minimum qualifications as – “Demonstrated experience with similar technologies at an enterprise scale”

Can the state provide the current technology stack?

**Comment by kelliejulian** [comment]
The technology is described in section 2.01 and 3.01
