### ISSUE TITLE
When will the State be providing answers to all questions that have been asked?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#102]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 1.12 – RFP Schedule, page 9 of 40
 
## Question/Comment

The RFP states that – “Deadline for receipt of questions on 3/1/2021 by 4:00 pm AKST”

When will the State be providing answers to all questions that have been asked?

**Comment by kelliejulian** [comment]
All questions have been answered as of 5pm 3/5/21.
