### ISSUE TITLE
What technology does the current MAGI Medicaid Eligibility and person search applications use?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#103]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 2.01 – BACKGROUND INFORMATION, page 11 of 40
 
## Question/Comment

This solicitation is for the support of the new modern eligibility platform. This platform currently contains MAGI Medicaid eligibility determination as well as a person search application. The eligibility product roadmap linked above contains plans to move all public assistance programs into one modern eligibility platform using a modular iterative approach. This support contract is for the express purpose of supporting this new modern integrated eligibility platform and all its components. The roadmap as well as the scope in section 3.01 list out those components.
 
What technology does the current MAGI Medicaid Eligibility and person search applications use?

**Comment by kelliejulian** [comment]
The person search application is built on JavaScript using the react framework. It uses two webservices that pull information from each of our eligibility platforms (EIS and ARIES).   Information about the current MAGI Medicaid eligibility platform can be found in sections 2.01 and 3.01.
