### ISSUE TITLE
Does the scope of this RFP include moving the remaining public assistance programs from the mainframe to the modern eligibility platform?  Will there be a separate RFP for moving the remaining applications?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#104]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 2.01 – BACKGROUND INFORMATION, page 11 of 40
 
## Question/Comment

This solicitation is for the support of the new modern eligibility platform. This platform currently contains MAGI Medicaid eligibility determination as well as a person search application. The eligibility product roadmap linked above contains plans to move all public assistance programs into one modern eligibility platform using a modular iterative approach. This support contract is for the express purpose of supporting this new modern integrated eligibility platform and all its components. The roadmap as well as the scope in section 3.01 list out those components.
 
Does the scope of this RFP include moving the remaining public assistance programs from the mainframe to the modern eligibility platform?  Will there be a separate RFP for moving the remaining applications?

**Comment by kelliejulian** [comment]
The scope of this RFP does not include moving programs from the mainframe to the modern platform. There will be multiple RFPs issued to handle that scope.
