### ISSUE TITLE
Will all the applications moved to the modern integrated eligibility platform be supported by the vendor as part of this contract?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#105]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 2.01 – BACKGROUND INFORMATION, page 11 of 40
 
## Question/Comment

This solicitation is for the support of the new modern eligibility platform. This platform currently contains MAGI Medicaid eligibility determination as well as a person search application. The eligibility product roadmap linked above contains plans to move all public assistance programs into one modern eligibility platform using a modular iterative approach. This support contract is for the express purpose of supporting this new modern integrated eligibility platform and all its components. The roadmap as well as the scope in section 3.01 list out those components.
 
Will all the applications moved to the modern integrated eligibility platform be supported by the vendor as part of this contract?

**Comment by kelliejulian** [comment]
This is answered in issue #96
