### ISSUE TITLE
Is this a pure Maintenance and Operations (M&O) procurement, or does it include design, development, testing and deployment of new functionality and enhancements?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#106]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 3.01 – Scope of Work, page 13 of 40
 
## Question/Comment

The RFP states in the scope of work – “Evaluation and implementation of system changes as a result of CMS updates, DPA priorities or new initiatives, state or federal mandates”

Is this a pure Maintenance and Operations (M&O) procurement, or does it include design, development, testing and deployment of new functionality and enhancements?

**Comment by kelliejulian** [comment]
The resulting contract will include changes and updates that could be considered new functionality or enhancements. For example, CMS mandates a small change to one of the existing in use hub services.
