### ISSUE TITLE
Please describe how and from whom will the successful vendor “Transition In”. 

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#107]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 3.03 – Transition Requirements, page 14 of 40
 
## Question/Comment

The RFP details only “Transition Out” requirements.

Please describe how and from whom will the successful vendor “Transition In”.

**Comment by kelliejulian** [comment]
We expect the successful vendor will integrate with the current State of Alaska team for both technical and process information/documentation. Please see [how we work](https://github.com/AlaskaDHSS/EIS-Modernization/blob/master/how-we-work.md)
