### ISSUE TITLE
Is this a mandatory discount that all Vendors are required to extend or can we opt out of this?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#108]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 3.09 – Prompt Payment for State Purchases, page 20 of 40
 
## Question/Comment

The RFP states that – “The state is eligible to receive a 5% discount for all invoices paid within 15 business days from the date of receipt of the commodities or services and/or a correct invoice, whichever is later.”

Is this a mandatory discount that all Vendors are required to extend or can we opt out of this?

**Comment by kelliejulian** [comment]
RFP section 3.09 - Prompt Payment for State Purchases, has been removed from the document.
