### ISSUE TITLE
We intend to perform work from our data center located in another state with travel to Alaska as required. Please confirm that we do not have to apply for an Alaska business license.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#109]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 3.12 – SUBCONTRACTORS, page 22 of 40
 
## Question/Comment

Note that if the subcontractor will not be performing work within Alaska, they will not be required to hold an Alaska business license.
 
We intend to perform work from our data center located in another state with travel to Alaska as required. Please confirm that we do not have to apply for an Alaska business license.

**Comment by kelliejulian** [comment]
This RFP section (3.11) only applies to subcontractors. For primary respondents, an Alaska business license will be required, section 6.02.
