### ISSUE TITLE
Does the State want vendors to describe this experience for each individual resource or to describe the vendor’s corporate experience with projects of similar scope and complexity?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#110]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 4.07 Experience and Qualifications, page 27 of 40
 
## Question/Comment

Most of this section asks vendors to provide information related to the vendor’s proposed resources. The last paragraph in that section reads, “Offerors must provide information describing work completed of a similar scope and complexity. Please provide experiences with similar technology software development, human-centered design, and continuous deployment methods.”

Does the State want vendors to describe this experience for each individual resource or to describe the vendor’s corporate experience with projects of similar scope and complexity?

**Comment by kelliejulian** [comment]
section 4.07 states: “The offeror must describe how they fully meet the minimum qualifications in section 1.04 and personnel criteria identified in section 3.04.

Offerors must also provide a narrative description of the organization of the project team and a personnel roster that identifies lines of authority. For each identified Key Staff member who will work on the contract, please provide the following:

Title and identification of the work this individual will be responsible for

Resume and specifically related work experience.

Offerors must provide information describing work completed of a similar scope and complexity. Please provide experiences with similar technology software development, human-centered design, and continuous deployment methods."  
Offerors must meet minimum qualifications as listed in section 1.04 with corporate experience. An offeror's failure to meet the requirements in section 1.04 will cause their proposal to be considered non-responsive and rejected. Key personnel requirements are listed in section 3.04.
