### ISSUE TITLE
Is the main intent of the demo to demonstrate the code management processes of the vendor?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#111]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 4.08 Verbal Presentation, page 27 pf 40
 
## Question/Comment

The RFP calls for a demo as part of the presentation.

Is the main intent of the demo to demonstrate the code management processes of the vendor?

**Comment by kelliejulian** [comment]
Yes
