### ISSUE TITLE
This RFP section states that the application is built on JAVA and is running on the described IBM stack. Is there a requirement for the demo to be running on Microsoft technologies, and if so, specifically which Microsoft components?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#112]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 4.08 Verbal Presentation, page 27 pf 40
 
## Question/Comment

The RFP calls for a demo as part of the presentation.

This RFP section states that the application is built on JAVA and is running on the described IBM stack. Is there a requirement for the demo to be running on Microsoft technologies, and if so, specifically which Microsoft components?

**Comment by kelliejulian** [comment]
There is not a technology requirement for the demo. We suggest that vendors review sections 2.01 and 3.01 to demonstrate similar technology types. This is described in section 4.08
