### ISSUE TITLE
Please elaborate on the technology that the State would prefer vendor demonstrations to utilize (e.g., JAVA, Microsoft Technologies, open sources). Please describe what technologies the current MAGI Medicaid application uses?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#113]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 4.08 – VERBAL PRESENTATION, page 27 pf 40
 
## Question/Comment

We strongly prefer a demonstration of a similar application built on like technology…. We are not interested in a demo or overview of an eligibility system that does not share similar technology and does not demonstrate the team’s ability to modify and maintain the State of Alaska Eligibility System….
 
Please elaborate on the technology that the State would prefer vendor demonstrations to utilize (e.g., JAVA, Microsoft Technologies, open sources). Please describe what technologies the current MAGI Medicaid application uses?

**Comment by kelliejulian** [comment]
This is described in section 4.08
