### ISSUE TITLE
Please confirm that a valid Alaska business license or proof of its application is not required at the time of proposal submission.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#114]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 6.02 – Alaska Business License and other Required Licenses, page 30 of 40
 
## Question/Comment

The RFP states that – “Prior to the award of a contract, an offeror must hold a valid Alaska business license.”

Please confirm that a valid Alaska business license or proof of its application is not required at the time of proposal submission.

**Comment by kelliejulian** [comment]
You do not need to hold an Alaska business license to submit a proposal, but it is recommended that one is obtained.  If the contract is awarded and a business license is not presented with a date prior to this the vendor will be considered non-responsive.
