### ISSUE TITLE
Please clarify as to what are these other necessary professional licenses that will be applicable for this procurement?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#115]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 6.02 – Alaska Business License and other Required Licenses, page 30 of 40
 
## Question/Comment

The RFP states that – “Prior to the deadline for receipt of proposals, all offerors must hold any other necessary applicable professional licenses required by Alaska Statute.”

Please clarify as to what are these other necessary professional licenses that will be applicable for this procurement?

**Comment by kelliejulian** [comment]
There are no professional licenses required for this procurement other than the Alaska business license.
