### ISSUE TITLE
Please provide the DHSS IT RFP IT Requirements template document.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#116]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

Attachment 10 IT Reference D - DHSS Information Technology Standards
 
## Question/Comment

1. Introduction 
This document is a reference companion to other documents, such as the DHSS IT RFP IT Requirements template, that clarifies the current IT standards.
 
Please provide the DHSS IT RFP IT Requirements template document.

**Comment by kelliejulian** [comment]
The documents referenced as companion documents are the attachments within this RFP package. Attachments 9,10,11,12.
