### ISSUE TITLE
Please elaborate on the following:

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#117]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

General
 
## Question/Comment

Please elaborate on the following:
a.	Number of applications currently in use and details about those applications – Purpose, technology used
b.	List of interfaces in use that the vendor will support
c.	List of reports in use (regular and ad hoc) 
d.	Number of records/ cases in the system
e.	Average number of incidents/defects opened and closed in a month

**Comment by kelliejulian** [comment]
We do plan to share all relevant information with the eventual successful bidder. Any needed information about the environment and scope can be found in section 2 and section 3. There are currently 26 interfaces in use. This number is subject to change based upon new initiatives and changes introduced by our partners. Over the last 90 days there have been 358 tickets created. These tickets have been of varying severity levels mostly skewing to lower severity.
