### ISSUE TITLE
How many Change Requirements (CR) are pending to be implemented for the project currently? 

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#119]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

3. Scope of work and Deliverables, page 12 of 40
 
## Question/Comment

The RFP states, “Evaluation and implementation of system changes as a result of CMS updates, DPA priorities or new initiatives, state or federal mandates”.  

How many Change Requirements (CR) are pending to be implemented for the project currently?

**Comment by kelliejulian** [comment]
We do plan to share all relevant information with the eventual successful bidder. Any needed information about the environment and scope can be found in section 2 and section 3. This is a time and materials contract.
