### ISSUE TITLE
Who will be responsible for enhancements during the contract term? Who will be responsible for defects and issues arising from any CRs or enhancements implemented during the contract period?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#120]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

3. Scope of work and Deliverables, page 12 of 40
 
## Question/Comment

The RFP states, “Evaluation and implementation of system changes as a result of CMS updates, DPA priorities or new initiatives, state or federal mandates”.  

Who will be responsible for enhancements during the contract term? Who will be responsible for defects and issues arising from any CRs or enhancements implemented during the contract period?

**Comment by kelliejulian** [comment]
This is a time and materials contract. Any defects or issues arising from any enhancements will be the responsibility of the support team to resolve.
