### ISSUE TITLE
Please provide the number of servers currently used to enable us to propose the right team size to meet State budget and requirements.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#121]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

3. Scope of work and Deliverables, page 12 of 40
 
## Question/Comment

The RFP states,” Each of these environments includes multiple virtual servers running windows 2008R2)”.

Please provide the number of servers currently used to enable us to propose the right team size to meet State budget and requirements.

**Comment by kelliejulian** [comment]
Server Count:    
Development -> 25 servers (24 servers-Windows 2008 R2/1 server-Windows   2016)   
Non-Prod -> 22 servers (20 servers-Windows 2008 R2/2 servers-Windows 2016)  
Production/DR -> 23 servers (21 severs-Windows 2008 R2/2 servers- Windows   2016)   
this information has been added to RFP section 2.01
