### ISSUE TITLE
Please provide the number of servers currently used in Azure and what type of OS is used, enabling us to propose the right team size to meet State budget and requirements.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#122]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

3. Scope of work and Deliverables, page 12 of 40
 
## Question/Comment

The RFP states,” Azure platform as a service”.

Please provide the number of servers currently used in Azure and what type of OS is used, enabling us to propose the right team size to meet State budget and requirements.

**Comment by kelliejulian** [comment]
We have three subscriptions in Azure. Development, Test, and Production.
