### ISSUE TITLE
Please provide the number of servers and software versions currently in use to enable us to propose the right team size to meet State budget and requirements.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#123]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

3. Scope of work and Deliverables, page 12 of 40
 
## Question/Comment

The RFP states,” IBM based technology stack”.

Please provide the number of servers and software versions currently in use to enable us to propose the right team size to meet State budget and requirements.

**Comment by kelliejulian** [comment]
See issue #121 as well as the information in 3.01
