### ISSUE TITLE
How can the vendor include annual rate increases during option years to accommodate cost of living adjustments, etc.?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#124]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

Attachment 1 – Cost Proposal
 
## Question/Comment

How can the vendor include annual rate increases during option years to accommodate cost of living adjustments, etc.?

**Comment by kelliejulian** [comment]
Attachment 1 - Cost Proposal has been updated
