### ISSUE TITLE
Who is responsible to acquire required software, licenses, etc. if the vendor’s capacity planning report deliverable identifies new capacity requirements? 

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#125]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

Section 3.06 DELIVERABLES, page 18 of 40
 
## Question/Comment

Who is responsible to acquire required software, licenses, etc. if the vendor’s capacity planning report deliverable identifies new capacity requirements?

**Comment by kelliejulian** [comment]
The purchase of software and licenses identified in the capacity planning report will be the responsibility of the State of Alaska technical team.
