### ISSUE TITLE
What is your current team size to support your current requirements?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#126]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

General
 
## Question/Comment

What is your current team size to support your current requirements?
-	DevOps
-	Triage
-	Development
-	Application Maintenance Team (Defect)
-	Testing
-	SecOps
-	Infrastructure
-	Business Analyst

**Comment by kelliejulian** [comment]
The Alaska technical team strategy is outlined in [how we work](https://github.com/AlaskaDHSS/EIS-Modernization/blob/master/how-we-work.md)
