### ISSUE TITLE
Currently who provides Help Desk functions for supporting the current applications? What is the process for escalation?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#127]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

General
 
## Question/Comment

Currently who provides Help Desk functions for supporting the current applications? What is the process for escalation?

**Comment by kelliejulian** [comment]
Help desk functions are provided by the State of Alaska with an internal escalation process providing support for users.
