### ISSUE TITLE
Current Environment and Support

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#36]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 2.01, Background
 
## Question/Comment

We recommend that the State provide additional details so that the vendor community has a more complete understanding of the current environment and support. This includes, but is not limited to, information on the following subject:
•	Current team organizational structure and general responsibilities
•	Help desk functions including the number of people supporting help desk, categories of calls, counts, etc. 
•	Tools and software used as well as relevant version information
•	Service ticket information, including the number of people supporting service tickets, categories of tickets (incident, problem, etc.), and counts
•	Modification requests, including the number of people supporting modifications, categories of requests, and counts

**Comment by nfaulknerAK** [comment]
Much of this information can be found in the document "Attachment 09 IT Reference A - DHSS IT Requirements Agile Acquisition" included in the RFP package. We do not intend to share more information at this time,  but will share all relevant information with the eventual successful bidder.
