### ISSUE TITLE
Page Limitations

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#37]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 4.01, Proposal Format and Content
 
## Question/Comment

We recommend that the State allow for more than 30 pages for the response to this RFP. Given the complexity of the system and the support plan, increasing this page limit will allow vendors to properly define their support model and expertise.

**Comment by nfaulknerAK** [comment]
We appreciate a targeted response. Note that the cost proposal, resumes and letters of intent are not included in this page limit and can be provided as attachments. The support plan deliverable is intended to be delivered after contract execution and should not be included in the proposal.
