### ISSUE TITLE
Architectural Diagrams and Batch Jobs

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#38]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State provide architectural and design diagrams for the ARIES system in the final RFP. Additionally, we recommend inclusion of information about the batch jobs and their complexity. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
We do not plan to share detailed and complete architectural diagrams at this time. We do plan to share all relevant information with the eventual successful bidder. Any needed information about the environment and scope can be found in section 2 and section 3.
There are currently 51 batch jobs running with different frequencies. The most infrequent run monthly.
