### ISSUE TITLE
Severity Level Definitions

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#39]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State provide the State’s definition for each severity level for incident tickets. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
Information has been added to section 3.01 to address this question.
