### ISSUE TITLE
Existing Production and Non-Production Environments

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#40]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State provide the existing production and non-production environments and how those are currently used. Additionally, we recommend inclusion of disaster recovery and business continuity planning information. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
The RFP will be updated as follows: Previously read:
Efficient business operations for both the technical support teams as well as the DPA business units
•	Maintaining current server and technology stack software versions

Now Reads:
Efficient business operations for both the technical support teams as well as the DPA business units
•	Maintaining current server and technology stack software versions (this includes a development, training/user testing, and production environment. Each of these environments includes multiple virtual servers running windows 2008R2)

Previously read:
•	Azure platform as a service
Now Reads:
•	Azure platform as a service (the person search application is hosted in Azure, with a development, test, and production instance). 

We don't intend to include DR/BC information at this time. The selected vendor will have access to this information.
