### ISSUE TITLE
Estimated Growth, Modernization, Enhancements

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#41]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State provide the estimated growth for the ARIES system over the next couple of years. Please include information on the anticipated modernization, enhancements, and number of users for the ARIES system. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
This information is contained in the ARIES Product Roadmap (https://app.mural.co/t/dhssalaska0106/m/dhssalaska0106/1576183680860/c1682951c77a41f29cb684cff893ff837f70b084) as well as the EIS modernization repository (https://github.com/AlaskaDHSS/EIS-Modernization). We expect the public assistance programs to continue to grow, but do not anticipate any unexpected user growth.
