### ISSUE TITLE
Roles and Responsibilities

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#42]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State provide details on the roles and responsibilities of the infrastructure, hosting, and data center for the vendor and the State. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
Information about the roles and responsibilites for infrastructure can be found in the RFP document "Attachment 09 IT Reference A - DHSS IT Requirements Agile Acquisition". RFP text will be changed as following: Previously read:
The MAGI Medicaid eligibility system is based on an IBM WebSphere software platform utilizing Microsoft Servers currently hosted on the State of Alaska virtual infrastructure.
The system communicates with multiple Federal and state partners to transfer information and documentation.
Now reads:
The MAGI Medicaid eligibility system is based on an IBM WebSphere software platform utilizing Microsoft Servers currently hosted on the State of Alaska virtual infrastructure. This virtual infrastructure is maintained by the Office of Information Technology under the Department of Administration. DHSS is currently responsible for the applications that run on this infrastructure. 
The current Azure infrastructure, in limited use, is managed by DHSS. 
The system communicates with multiple Federal and state partners to transfer information and documentation.
