### ISSUE TITLE
Migration to Cloud

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#43]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01, Scope of Work
 
## Question/Comment

We recommend that the State clarify if the expectation of the vendor is to migrate the ARIES system to the cloud or if that is outside the scope of the RFP. This information will allow vendors to properly estimate the support needed for the ARIES system.

**Comment by nfaulknerAK** [comment]
The migration of the ARIES system to the cloud is not in scope for this effort. The selected vendor will be expected to work with a chosen migration vendor, but the responsibility for the migration will not result from this procurement.
