### ISSUE TITLE
Fixed M&O Price by Period

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#44]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Attachment 01, Cost Proposal
 
## Question/Comment

We recommend that Attachment 01 Cost Proposal of the State's final RFP contain fixed maintenance and operations price by period, instead of detailed pricing by role for each period. A total fixed price for each period allows vendors more flexibility to incorporate efficiencies and staffing adjustments through the life of the contract. This will provide the State with more price-efficient and competitive bids.

**Comment by nfaulknerAK** [comment]
At this time the cost proposal will not be changing. This contract will be a time and materials contract with a do not exceed amount.
