### ISSUE TITLE
Transition Project Schedule

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#45]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.06, Deliverables
 
## Question/Comment

We recommend the inclusion of a transition project schedule in the list of deliverables. This formal deliverable will ensure that all parties agree on the schedule of activities, dates, milestones, and resources.

**Comment by nfaulknerAK** [comment]
A transition plan deliverable has been added to Section 3.06.
