### ISSUE TITLE
Interface Control Document

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#46]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.06, Deliverables
 
## Question/Comment

We recommend the inclusion of an interface control document in the list of deliverables. This formal deliverable will ensure that there is a shared understanding of what interfaces need to be managed and monitored, who is responsible for those tasks, and identify the appropriate points of contact.

**Comment by nfaulknerAK** [comment]
We don't intend to make the interface list a formal deliverable, however we will share the exact interfaces as well as the documentation for each to the successful bidder. There are currently 26 interfaces in use. This number is subject to change based upon new inititives and changes introduced by our partners.
