### ISSUE TITLE
Transition Approval Notice

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#47]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.06, Deliverables
 
## Question/Comment

We recommend the inclusion of a transition approval notice in the list of deliverables. This formal deliverable will signify the completion of the transition and will formally close that phase of the project.

**Comment by nfaulknerAK** [comment]
Agree. A transition plan deliverable has been added to Section 3.06.
