### ISSUE TITLE
Alaska Bidder Preference

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#48]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 5.07, Contract Cost
 
## Question/Comment

We recommend that, if applicable, the State include details associated with the Alaska Bidder Preference – AS 36.30.321(A)/AS 36.30.990 (2).

**Comment by nfaulknerAK** [comment]
This solicitation will not be using Alaska bidder preference as a scoring criteria for selection
