### ISSUE TITLE
System Identification for M&O

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#49]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 2.01, Background Information
 
## Question/Comment

We recommend that the State clearly identify the system(s) for which the contractor will be responsible for maintenance and operations, to facilitate estimates and staffing.

**Comment by nfaulknerAK** [comment]
Information has been added to section 2.01 to address this question.
