### ISSUE TITLE
Minimum Qualifications

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#51]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Sec. 1.04 Minimum Qualifications
 
## Question/Comment

We recommend changing the minimum qualification “a minimum of three (3) years' experience in the last five (5) years, conducting Health and Human Services system support operations services” to “a minimum of three (3) years' experience in the last five (5) years, conducting enterprise system support operations services for large government agencies” in order to consider vendors who have highly relevant experience that is not for Health and Human Services, such as experience with licensing eligibility systems, tax systems, and other benefits eligibility systems.

**Comment by nfaulknerAK** [comment]
We have updated this qualification to the following. "Contractor must have a minimum of three (3) years' experience in the last five (5) years, conducting health or human services system support operations services. This experience must include maintenance and updates of an enterprise technology system".
