### ISSUE TITLE
Project Manager Qualifications

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#52]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Sec. 3.04 Personnel
 
## Question/Comment

We recommend changing the minimum qualification that the proposed Project Manager “must have a minimum of three (3) years’ experience in the last five (5) years leading a project for a Medicaid enterprise system” to “must have a minimum of three (3) years’ experience in the last five (5) years leading a project for an enterprise system” in order to consider project managers who have other highly relevant experience leading projects for similar enterprise systems that are not Medicaid systems.

**Comment by nfaulknerAK** [comment]
We have changed section 3.04 to match the language in section 1.04. The new qualification will read " The Project Manager must have a minimum of three (3) years’ experience in the last five (5) years leading a project for a health or human services agency.
