### ISSUE TITLE
Project Scope

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#53]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Section 3. Scope of Work and Deliverables
 
## Question/Comment

We recommend that DHSS consider breaking the scope of this contract into multiple solicitations: one solicitation for a vendor to provide technical support services and one solicitation for a vendor with Medicaid eligibility expertise to provide project oversight and quality assurance. We believe this approach would provide the highest value to the state by allowing you to contract with the best vendor in each area.

**Comment by nfaulknerAK** [comment]
We appreciate the feedback. However, we feel the scope of work envisioned as part of this RFP is narrow enough to be handled in a single procurement. It's worth noting that subcontracting is allowed as part of responding to the RFP.
