### ISSUE TITLE
Verbal Presentation and Demo

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#54]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Sec. 4.08 Verbal Presentation
 
## Question/Comment

We don’t understand the objectives of the software demo portion of the verbal presentations, as DHSS intends to keep your existing systems and procure support services.  While our company does support systems for government agencies, those agencies would not allow us to demo their systems, making the software demo portion difficult or impossible for us.

**Comment by nfaulknerAK** [comment]
The demo portion of the verbal presentation is intended to show the offerors ability to build an application or even a simple prototype on like technology. The demo is also intended to show how the offerors technical team could manage software build and deploy using similar porcesses to how DHSS would like to work. This demo is optional, however it will impact scoring. Section 4.08 states "This could include a short overview of an application that is built in JAVA and running on IBM WebSphere, or changes to an application that is already running on a similar technology stack. Of special note would be a demonstration of code management processes where multiple teams are working on a single code base including tools, testing, and process control. We are not interested in a demo or overview of an eligibility system that does not share similar technology and does not demonstrate the team's ability to modify and maintain the State of Alaska Eligibility System" is relevant to the demo portion of the verbal presentation.
