### ISSUE TITLE
Alaska Offeror Preference/Alaska Bidder Preference

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#55]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Section 5. Evaluation Criteria and Contractor Selection
 
## Question/Comment

We recommend that DHSS consider adding the Alaska Offeror Preference to the Evaluation Criteria and the Alaska Bidder Preference to the price evaluation.

**Comment by nfaulknerAK** [comment]
This solicitation will not be using Alaska bidder preference as a scoring criteria for selection.
