### ISSUE TITLE
Procurement approach 

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#56]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

N/A

## Question/Comment

We recommend DHSS consider following the State of Alaska’s Best Value approach to procurement for this solicitation in order to consider a wide range of vendors and then narrow the field of vendors during evaluation and interviews.

**Comment by nfaulknerAK** [comment]
We have chosen at this time to not implement the best value approach. Please note that this solicitation does not include price as the only criteria for evaluation.
