### ISSUE TITLE
Previous ARIES Support

### ISSUE THREAD

**Issue by nmartin-rdi** [AlaskaDHSS/RFP-ARIES-Support#57]
## Name and affiliation

Natalie Martin, Proposal Team Manager, Resource Data

## Section of RFP documents

Section 3. Background Information

## Question/Comment

Is ARIES currently supported internally by DHSS or by a vendor? If a vendor has been supporting it, what vendor?

**Comment by nfaulknerAK** [comment]
The application is currently supported by DHSS.
