### ISSUE TITLE
RFP Scope

### ISSUE THREAD

**Issue by Nava-Team** [AlaskaDHSS/RFP-ARIES-Support#77]
## Section of RFP documents

3.01 Scope of Work
 
## Question/Comment

Is moving DPA programs from the legacy system onto ARIES in scope for this RFP? If not, are you planning to issue a separate RFP for that work? If so, would the vendor selected as a result of this RFP be eligible to bid on that RFP or any other ARIES system-related procurements? Can you please provide a list of other planned ARIES-related procurements? Thank you.

**Comment by kelliejulian** [comment]
Moving programs from the Legacy EIS into the modern eligibility system is not in scope for this RFP. Being awarded this contract should not preclude an offeror from bidding on any future roadmap RFPs. Many of the product increments listed out in the [Alaska ARIES Product    roadmap](https://app.mural.co/t/dhssalaska0106/m/dhssalaska0106/1576183680860/c1682951c77a41f29cb684cff893ff837f70b084) will have a corresponding RFP. Some examples are automated application processing in milestone 1 increment 4 (may be multiple RFPs) and RFP releases for the addition of more Medicaid categories.
--
