### ISSUE TITLE
Batch Jobs

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#79]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01 Scope of Work

##Question
 
Will the State please provide information about the batch jobs and their complexity (e.g., number of batch jobs)?

**Comment by kelliejulian** [comment]
This was answered here. 
https://github.com/AlaskaDHSS/RFP-ARIES-Support/issues/38
--
