### ISSUE TITLE
Number of Servers to Migrate

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#80]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 3.01 Scope of Work
 
## Question/Comment

Will the State provide the number of servers that need to be migrated to Windows Servers 2016?

**Comment by kelliejulian** [comment]
RFP has been amended as follows.   Section 2.01 "The MAGI Medicaid eligibility system is based on an IBM   WebSphere software platform utilizing Microsoft Servers currently hosted on   the State of Alaska virtual infrastructure. This virtual infrastructure is   maintained by the Office of Information Technology under the Department of   Administration. DHSS is currently responsible for the applications that run   on this infrastructure."    
will now read     
"The MAGI Medicaid eligibility system is based on an IBM WebSphere   software platform utilizing Microsoft Servers currently hosted on the State   of Alaska virtual infrastructure. This virtual infrastructure is maintained   by the Office of Information Technology under the Department of   Administration. DHSS is currently responsible for the applications that run   on this infrastructure. This environment currently contains:   
Server Count    
Development -> 25 servers (24 servers-Windows 2008 R2/1 server-Windows   2016)   
Non-Prod -> 22 servers (20 servers-Windows 2008 R2/2 servers-Windows 2016)   Production/DR -> 23 servers (21 severs-Windows 2008 R2/2 servers- Windows   2016)”
--
