### ISSUE TITLE
Ticket Volume and Severity

### ISSUE THREAD

**Issue by kmanna223** [AlaskaDHSS/RFP-ARIES-Support#84]
## Name and affiliation

Business Development, Optum

## Section of RFP documents

Section 2.01 Background
 
## Question/Comment

For tickets that the State expects to assign to the Contractor, will the State please provide your volume of tickets and their severity for the past 90 days?

**Comment by kelliejulian** [comment]
Over the last 90 days there have been 358 tickets created. These tickets have been of varying severity levels mostly skewing to lower severity.
