### ISSUE TITLE
Request for an Extension

### ISSUE THREAD

**Issue by deyosue** [AlaskaDHSS/RFP-ARIES-Support#85]
## Name and affiliation

{Proposal Manager with eSystems

Section1.12 RFP Schedule
{please be specific about the section of the RFP documents you have a question or comment about, if applicable}
 
## Question/Comment

The current schedule is very tight. Would the State consider a 4 week extension vendors can prepare a meaningful and quality response and appropriate price to meets Alaska’s needs.

**Comment by kelliejulian** [comment]
We will be extending the submission   deadline to 3/26/2021 at 4PM Alaska Prevailing Time.
