### ISSUE TITLE
eSystems Questions for ARIES System Support

### ISSUE THREAD

**Issue by deyosue** [AlaskaDHSS/RFP-ARIES-Support#87]
## NamSue Deyo - eSystems Proposal Manager
[eSystems_Alaska ARIES Support_Questions.docx](https://github.com/AlaskaDHSS/RFP-ARIES-Support/files/6064888/eSystems_Alaska.ARIES.Support_Questions.docx)
[eSystems_Alaska ARIES Support_Questions.docx](https://github.com/AlaskaDHSS/RFP-ARIES-Support/files/6064891/eSystems_Alaska.ARIES.Support_Questions.docx)

{please provide information about your job/role in the acquisition process as well as your organization}

## Section of RFP documents

{please be specific about the section of the RFP documents you have a question or comment about, if applicable}
 
## Question/Comment

{ask away!}

**Comment by nfaulknerAK** [comment]
All of the attached questions have been moved to their own individual issues #92-#127.
