### ISSUE TITLE
Deadline for Receipt of Proposals

### ISSUE THREAD

**Issue by PYXISMCG** [AlaskaDHSS/RFP-ARIES-Support#88]
## Name and affiliation

PYXIS Management Consulting Group

## Section of RFP documents

Section 1.03
 
## Question/Comment

We respectfully request an extension to the proposal submission date. In order to submit a quality proposal, we are requesting for 4 weeks extension from all answers to the questions submitted by today.

**Comment by kelliejulian** [comment]
We will be extending the submission   deadline to 3/26/2021 at 4PM Alaska Prevailing Time.
