### ISSUE TITLE
Transition In/Takeover by a New Vendor

### ISSUE THREAD

**Issue by PYXISMCG** [AlaskaDHSS/RFP-ARIES-Support#89]
## Name and affiliation

PYXIS Management Consulting Group

## Section of RFP documents

Section 3.03
 
## Question/Comment

Based on our experience of Transitioning in (takeover) from another organization in multiple states, the new vendor goes through a knowledge acquisition period.  Could we describe our approach in the proposal Section 4.04?

**Comment by kelliejulian** [comment]
Section 3.03 requirements are specifically aimed at the transition from this resulting contract to another organization or to the State of Alaska. Any information you would provide about that, or the successful transition into the resulting contract could be provided in Section 4.
