### ISSUE TITLE
Hosting of EIS' Functional Modules

### ISSUE THREAD

**Issue by PYXISMCG** [AlaskaDHSS/RFP-ARIES-Support#90]
## Name and affiliation

PYXIIS Management Consulting Group

## Section of RFP documents

Section 3.01
 
## Question/Comment

Could you please confirm EIS’ core functional modules (Screening, Intake, EDBC, Authorization, Benefit Insurance, Benefit Recovery, Client Correspondence, Interfaces etc.)  are in on-premise location?   Has self-service portal been implemented and is it in on-premise location?

{ask away!}

**Comment by kelliejulian** [comment]
All core functions of the MAGI Medicaid eligibility system (ARIES) are currently hosted in a State of Alaska Data Center. There is one application (person search) that is hosted in a DHSS controlled and managed Azure environment. As described in section 3.01 we expect more functions to move to Azure. There is a self-service portal for MAGI Medicaid application. It is hosted in a State of Alaska data center. This information is expanded upon in section 3.01.
