### ISSUE TITLE
EIS Application Architecture

### ISSUE THREAD

**Issue by PYXISMCG** [AlaskaDHSS/RFP-ARIES-Support#91]
## Name and affiliation

PYXIIS Management Consulting Group

## Section of RFP documents

Section 2.01

## Question/Comment

We are not able to locate an Application Architecture document in GitHub. Could you please provide EIS Application Architecture document?

**Comment by kelliejulian** [comment]
We do not plan to share detailed and complete architectural diagrams at this time. We do plan to share all relevant information with the eventual successful bidder. Any needed information about the environment and scope can be found in section 2 and section 3.
