### ISSUE TITLE
Who is the incumbent currently maintaining the public assistance eligibility system that processes eligibility for MAGI Medicaid?

### ISSUE THREAD

**Issue by nfaulknerAK** [AlaskaDHSS/RFP-ARIES-Support#94]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Cover Page, page 1 of 40
 
## Question/Comment

The   RFP states that – “The Alaska Department of Health and Social Services   (DHSS), Division of Public Assistance (DPA) is searching for a partner to   support the ongoing maintenance of the public assistance eligibility system.   This system currently processes eligibility for MAGI Medicaid but is growing   to support all existing public assistance programs.”        

Who   is the incumbent currently maintaining the public assistance eligibility   system that processes eligibility for MAGI Medicaid?

**Comment by kelliejulian** [comment]
The system is currently maintained by the State of Alaska.
