### ISSUE TITLE
Who is the incumbent currently developing necessary enhancements to the public assistance eligibility system to support all existing public assistance programs?

### ISSUE THREAD

**Issue by nfaulknerAK** [AlaskaDHSS/RFP-ARIES-Support#95]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Cover Page, page 1 of 40
 
## Question/Comment

The RFP states that – “The Alaska Department of Health and Social Services (DHSS), Division of Public Assistance (DPA) is searching for a partner to support the ongoing maintenance of the public assistance eligibility system. This system currently processes eligibility for MAGI Medicaid but is growing to support all existing public assistance programs.”

Who is the incumbent currently developing necessary enhancements to the public assistance eligibility system to support all existing public assistance programs?

**Comment by kelliejulian** [comment]
There have been multiple vendors selected to develop and implement enhancements and new functionality for the eligibility system. This strategy is best described [here](https://github.com/AlaskaDHSS/EIS-Modernization#methods--strategies)
