### ISSUE TITLE
Is this contract scope intended to cover the support and maintenance of all additional programs as they are added to the new eligibility system? 

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#96]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Cover Page, page 1 of 40
 
## Question/Comment

The RFP cover page describes that the purpose is to find a partner to support the ongoing maintenance of the public assistance eligibility system, Aries, and that this system currently processes eligibility for MAGI Medicaid but is growing to support all existing public assistance programs.

Is this contract scope intended to cover the support and maintenance of all additional programs as they are added to the new eligibility system?

**Comment by kelliejulian** [comment]
The resulting contract will be a time and materials contract, and will include newly developed and implemented programs. As the environment changes and grows we expect to have conversations about the appropriate prioritization to ensure that the time and materials nature of the resulting contract can be completed successfully.
