### ISSUE TITLE
Please provide timelines (or estimates) for the onboarding of additional programs beyond MAGI Medicaid, including the program names?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#97]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Cover Page, page 1 of 40
 
## Question/Comment

The RFP cover page describes that the purpose is to find a partner to support the ongoing maintenance of the public assistance eligibility system, Aries, and that this system currently processes eligibility for MAGI Medicaid but is growing to support all existing public assistance programs.

Please provide timelines (or estimates) for the onboarding of additional programs beyond MAGI Medicaid, including the program names?

**Comment by kelliejulian** [comment]
The ARIES product roadmap outlines the prioritized plans to move programs out of the legacy eligibility system (EIS) and into the modern platform. We anticipate completion of the currently outlined product roadmap scope and milestones within the next 5 years.
