### ISSUE TITLE
Is there another vendor that is, or will be contracted to design, develop and implement the addition of other program areas on ARIES, or do you anticipate that the selected vendor from this RFP may get additional scope of work for this effort in the future?

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#98]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Cover Page, page 1 of 40
 
## Question/Comment

The RFP cover page describes that the purpose is to find a partner to support the ongoing maintenance of the public assistance eligibility system, Aries, and that this system currently processes eligibility for MAGI Medicaid but is growing to support all existing public assistance programs.

Is there another vendor that is, or will be contracted to design, develop and implement the addition of other program areas on ARIES, or do you anticipate that the selected vendor from this RFP may get additional scope of work for this effort in the future?

**Comment by kelliejulian** [comment]
We plan to release multiple RFPs to engage with a vendor or vendors to build and implement roadmap product increments. The successful vendor for the ARIES support scope of work will not be disqualified from submitting proposals for future roadmap RFPs.
