### ISSUE TITLE
In order to allow sufficient time to put together a proposal after receipt of answers to questions from the Department, we would like to request that the proposal due date be extended by at least 4 weeks.

### ISSUE THREAD

**Issue by tracymack** [AlaskaDHSS/RFP-ARIES-Support#99]
## Name and affiliation

Sue Deyo - eSystems Proposal Manager

## Section of RFP documents

RFP Sec. 1.03 – Deadline for Receipt of Proposals, page 5 of 40
 
## Question/Comment

The RFP states that – “Proposals must be received no later than 4:00 pm prevailing Alaska Time on 3/12/2021.”

In order to allow sufficient time to put together a proposal after receipt of answers to questions from the Department, we would like to request that the proposal due date be extended by at least 4 weeks.

**Comment by kelliejulian** [comment]
We will be extending the submission deadline to 3/26/2021 at 4PM Alaska Prevailing Time.
